---
  # Site.yml to manage the ServerDelivery Playbook.

- hosts: all
  remote_user: root
  vars_files:
    - group_vars/main.yml
    - group_vars/passes.yml


  tasks:
    - name: update all YUM packages to latest
      yum:
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_os_family == "RedHat"

      tags:
        - redhat
        - update

    - name: update all Apt packages to latest
      apt:
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_os_family == "Debian"

      tags:
        - debian
        - update

    - name: adding users to servers
      user:
        name: "{{ item }}"
        comment: "{{ item }} sudo account"
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_file: .ssh/id_rsa
        ssh_key_bits: 4096
        ssh_key_type: rsa
        ssh_key_comment: "{{ item }}@{{ ansible_hostname }}"
        ssh_key_passphrase: "{{ users_ssh_key_pass }}"
      with_items: "{{ delivered_users }}"

      tags:
        - users
